# Generated by Django 5.1.15 on 2026-09-18 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Used by website code, e.g. 'login'", max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('event', 'Website event'), ('inactivity', 'Inactivity')], default='event', max_length=20)),
                ('inactivity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('webpush', 'Web Push')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, help_text='Use {{variables}} like {{name}}, {{site_name}}')),
                ('cta_label', models.CharField(blank=True, max_length=60)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('footer', models.CharField(blank=True, max_length=60)),
                ('push_ios', models.BooleanField(default=False)),
                ('push_android', models.BooleanField(default=False)),
                ('wa_name', models.CharField(blank=True, max_length=512)),
                ('wa_language', models.CharField(default='en_US', max_length=15)),
                ('wa_category', models.CharField(choices=[('UTILITY', 'Utility'), ('MARKETING', 'Marketing'), ('AUTHENTICATION', 'Authentication')], default='UTILITY', max_length=20)),
                ('wa_use_existing', models.BooleanField(default=False, help_text='Link a template that already exists in Meta')),
                ('wa_template_id', models.CharField(blank=True, max_length=64)),
                ('wa_status', models.CharField(choices=[('DRAFT', 'Not submitted'), ('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled by Meta'), ('ERROR', 'Submit failed')], default='DRAFT', max_length=20)),
                ('wa_status_reason', models.CharField(blank=True, max_length=500)),
                ('variable_mapping', models.JSONField(blank=True, default=list)),
                ('wa_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.trigger')),
            ],
            options={
                'ordering': ['trigger__position', 'channel'],
                'unique_together': {('trigger', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='TriggerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notifications.trigger')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('webpush', 'Web Push')], max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=10)),
                ('is_test', models.BooleanField(default=False)),
                ('rendered_title', models.CharField(blank=True, max_length=255)),
                ('rendered_body', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.template')),
                ('trigger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.trigger')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.triggerevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
